### ISSUE TITLE
    parser.parsingHeadersStart = nowDate();

### ISSUE THREAD

**Issue by elieobeid7** [franciscop/server#117]
Trying to run websockets example here, just copying and pasting

https://github.com/franciscop/server/tree/master/examples/websocket

I get

```
_http_server.js:744
    parser.parsingHeadersStart = nowDate();
                               ^

TypeError: Cannot set property 'parsingHeadersStart' of undefined
    at IncomingMessage.resetHeadersTimeoutOnReqEnd (_http_server.js:744:32)
    at IncomingMessage.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by elieobeid7** [comment]
This project is dead, closing the issue, use another project like uwebsocketsjs or whatever
