### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by vorticalbox** [franciscop/server#20]
been following https://serverjs.io/tutorials/getting-started/

when i start the server i get 

`/mnt/Documents/node/chat/node_modules/server/server.js:21
const Server = async (...middle) => {
                     ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/Documents/node/chat/index.js:2:16)`

ubuntu 17.10 node 6.11.4

**Comment by franciscop** [comment]
Hi @vorticalbox,

I thought that node would throw a more obvious error before letting you run the code since the [`package.json`](https://github.com/franciscop/server/blob/master/package.json) specifies the engine. The minimum version for server is Node 7.6, and the recommended one is the recently released LTS 8.9.0. I will leave this open until I update that guide.

**Comment by vorticalbox** [comment]
Thea is for the heads up ill update my node.
