### ISSUE TITLE
views option not worked

### ISSUE THREAD

**Issue by Oisrrmy** [franciscop/server#27]
I followed the document from the website to set views option, but it not worked.
The server looked up default views path and ignore my option, is anything wrong?
This my code:

```js
// app.js
server({
  'port': 3000,
  'public': 'public',
  'engine': 'ejs',
  'views': './src/views'
}, [
  get('/', ctx => render('index'))
])
```

logout:

```
ERROR { Error: Failed to lookup view "index" in views directory "****/Demo/views"
    at Function.render (****/Demo/node_modules/express/lib/application.js:580:17)
    at ServerResponse.render (****/Demo/node_modules/express/lib/response.js:1008:7)
    at Promise (****/Demo/node_modules/server/reply/reply.js:124:13)
    at Promise (<anonymous>)
    at stack.push.ctx (****/Demo/node_modules/server/reply/reply.js:121:26)
    at Reply.exec (****/Demo/node_modules/server/reply/reply.js:157:11)
    at processReturn (****/Demo/node_modules/server/src/join/index.js:11:22)
    at ****/Demo/node_modules/server/src/join/index.js:41:17
    at <anonymous>
  view: 
   View {
     defaultEngine: 'ejs',
     ext: '.ejs',
     name: 'index',
     root: '****/Demo/views',
     engine: [Function],
     path: undefined } }
```

**Comment by LeelaVenkateshK** [comment]
is someone working on this? Please let me know. I would like to try to fix this issue

**Comment by franciscop** [comment]
Please feel free to help out here, I won't have much time until the weekend to have a go at this.

**Comment by franciscop** [comment]
Upgrade to the `1.0.4` to get this fixed.
