### ISSUE TITLE
internal error when adding new routes

### ISSUE THREAD

**Issue by vorticalbox** [franciscop/server#29]
I Followed the chat tutorial and to learn more by expanding it, The issue I am currently having is adding new gets in this case a rules page

`
server({port: 8080},[
  get('/', ctx => render('index.html')),
  get('/rules', ctx => render('rules.html')),
  socket('connect', updateCounter),
  socket('disconnect', updateCounter),
  socket('message', sendMessage)
]);
`

in the browser gives Internal Server Error, no errors in the console

**Comment by ghvaldez** [comment]
Hello @vorticalbox I just completed the getting started and chat tutorial found [here](https://serverjs.io/tutorials/chat/)  I was able to the last step and run the app locally via `node .` step.  Where exactly did you run into this error?

**Comment by ghvaldez** [comment]
@vorticalbox ahh I see now what you were trying to do.  Maybe I have different settings for my local install of node but I saw this error in my console.

```ERROR { Error: Failed to lookup view "rules.html" in views directory "/Users/gvaldez/Documents/development/server-test/views"
    at Function.render (/Users/gvaldez/Documents/development/server-test/node_modules/express/lib/application.js:580:17)
    at ServerResponse.render (/Users/gvaldez/Documents/development/server-test/node_modules/express/lib/response.js:1008:7)
    at Promise (/Users/gvaldez/Documents/development/server-test/node_modules/server/reply/reply.js:124:13)
    at Promise (<anonymous>)
    at stack.push.ctx (/Users/gvaldez/Documents/development/server-test/node_modules/server/reply/reply.js:121:26)
    at Reply.exec (/Users/gvaldez/Documents/development/server-test/node_modules/server/reply/reply.js:157:11)
    at processReturn (/Users/gvaldez/Documents/development/server-test/node_modules/server/src/join/index.js:11:22)
    at /Users/gvaldez/Documents/development/server-test/node_modules/server/src/join/index.js:41:17
    at <anonymous>
  view:
   View {
     defaultEngine: 'pug',
     ext: '.html',
     name: 'rules.html',
     root: '/Users/gvaldez/Documents/development/server-test/views',
     engine: [Function: bound middleware],
     path: undefined } }```

After adding a directory named `views` as a peer to `public` aka at the root of the project and moved the `rules.html` file there....everything works

**Comment by franciscop** [comment]
@vorticalbox could you share your project file structure please? Does the error happen on startup, on an specific page or on all pages?
