### ISSUE TITLE
server/reply/cookie =>`TypeError: option expires is invalid`

### ISSUE THREAD

**Issue by bodhisattva082915** [franciscop/server#36]
In returning a cookie response I'm attempting to set the expiration date of the cookie. Following the express docs, options object has an expires key. Below is the code that causes the error.

```
    const portalAccessToken = authService.generateToken(user);
        return status(200).cookie('accessToken', portalAccessToken, {
            httpOnly: true,
            expires: new Date()
    });
```

[Mon Nov 13 2017 22:09:33 GMT+0000 (UTC)] WARNING There is an unhandled error:
[Mon Nov 13 2017 22:09:33 GMT+0000 (UTC)] ERROR TypeError: option expires is invalid
    at Object.serialize (/usr/app/node_modules/cookie/index.js:145:13)
    at ServerResponse.res.cookie (/usr/app/node_modules/express/lib/response.js:853:36)
    at stack.push.ctx (/usr/app/node_modules/server/reply/reply.js:20:13)
    at Reply.exec (/usr/app/node_modules/server/reply/reply.js:157:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by bodhisattva082915** [comment]
Found this issue. Was setting the cookie to expire currently. Setting the cookie to expire later fixes the issue.

**Comment by franciscop** [comment]
No problem, glad you could fix it :+1:
