### ISSUE TITLE
about express use method need a path arguments sample

### ISSUE THREAD

**Issue by MiYogurt** [franciscop/server#57]
the express sample

```js
var PouchDB = require('pouchdb');
var express = require('express');
var app = express();

app.use('/db', require('express-pouchdb')(PouchDB));

app.listen(3000);
```

I try in my router.js

```js
import server from 'server'
import { sub } from 'server/router'
import PouchDB from 'pouchdb'
const { modern } = server.utils

export default [
    sub('db', modern(
        require('express-pouchdb')
        (PouchDB)
    )),
    ctx => 'Hello world'
]
```

```bash
➜ http :10087/db
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 11
Content-Type: text/html; charset=utf-8
Date: Fri, 12 Jan 2018 06:39:46 GMT
ETag: W/"b-e1AsOh9IyGCa4hLN+2Od7jlnP14"
Strict-Transport-Security: max-age=15552000; includeSubDomains
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-DNS-Prefetch-Control: off
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
set-cookie: connect.sid=s%3A1_Z_VAiCK6pH8KRMsFEW6OZ3lyF5QK2o.R9vH2IoG0gp218Z5OUyGkWLeLox4S0HecoGcxkQ0M8I; Path=/; HttpOnly

Hello world
```

how to write the sample code if i use server.js ?

**Comment by franciscop** [comment]
Interesting issue, the `sub()` router is for subdomains, not for routes mounting points. AFAIK there is no really a native way of doing this with server.js and this is the first time I see a compelling reason for adding it. What you do you'd have to request `https://db.example.com/` (after also configuring the DNS for that).

Will probably come with the 1.1 as `use()`, but so far you can use this workaround:

```js
// ...

const pouch = ctx => {
  return modern(ctx.app.use('/db', require('express-pouchdb')(PouchDB))(ctx);
};

server(pouch, ctx => 'Hello World');
```

This way we are using the native express router. Note that, as mentioned, this is a workaround. Also, this will leak the route so if you later have a server.js router matching `/db/` it will **also** be called. This is default in express, but purposefully disabled in server.js to avoid errors.

Please let me know if that works for you, and thanks for using server.js!

**Comment by MiYogurt** [comment]
my code is

```js
import server from 'server'
const { modern } = server.utils
import PouchDB from 'pouchdb'

const pouch = ctx => {
  return modern(
    ctx.app.use('/db', require('express-pouchdb')(PouchDB)))(ctx);
};

const ExpressMiddleware = [

].map(modern);

const middleware = [
    pouch
]

export default [
    ...ExpressMiddleware,
    ...middleware
];
```

it does not work.

```bash
PouchPluginError {
  status: 500,
  name: 'already_active',
  message: 'Replicator already active on this database.',
  error: true,
  stack: 'Error\n    at new PouchPluginError (/Users/Yugo/Desktop/lolo-ci/node_modules/pouchdb-plugin-error/index.js:24:17)\n    at PouchDB$5.exports.startReplicatorDaemon (/Users/Yugo/Desktop/lolo-ci/node_modules/pouchdb-replicator/lib/index.js:59:27)\n    at /Users/Yugo/Desktop/lolo-ci/node_modules/express-pouchdb/lib/replicator.js:61:21\n    at <anonymous>' } Promise {
  <rejected> PouchPluginError {
  status: 500,
  name: 'already_active',
  message: 'Replicator already active on this database.',
  error: true,
  stack: 'Error\n    at new PouchPluginError (/Users/Yugo/Desktop/xxx/node_modules/pouchdb-plugin-error/index.js:24:17)\n    at PouchDB$5.exports.startReplicatorDaemon (/Users/Yugo/Desktop/xxx/node_modules/pouchdb-replicator/lib/index.js:59:27)\n    at /Users/Yugo/Desktop/xxx/node_modules/express-pouchdb/lib/replicator.js:61:21\n    at <anonymous>' } }
```

if i use express sample code ，everything it is ok ，does not need to do any more thing。 i think it's must have some Compatibility problem。 

i am give up use express-pouchdb

```js
import PouchDB from 'pouchdb'
import websql from 'pouchdb-adapter-node-websql'

PouchDB.plugin(websql);

if(process.env.LOLO_ENV != 'prod') PouchDB.debug.enable('*');

const ci = new PouchDB('lolo_ci', {adapter: 'websql'});
const logs = new PouchDB('lolo_logs',{adapter: 'websql'});

export {
    ci,
    logs
}
```

**Comment by franciscop** [comment]
My mistake, please try with this:

```js
const pouch = ctx => {
  ctx.app.use('/db', require('express-pouchdb')(PouchDB));
};
```

We are injecting it to express already, so no need to return it since it would be called again. I think that is what the error `'Replicator already active on this database.'` might mean.
