### ISSUE TITLE
Nunjucks broken using engine = {nunjucks: } on Server.js Version server@1.1.0-alpha.3

### ISSUE THREAD

**Issue by coderam** [franciscop/server#82]
### Description

after running node index.js on the new server@1.1.0-alpha.3 version and attempting to use the new engine = {nunjucks: }, server.js fails with "Error: Module "nunjucks" does not provide a view engine."

The code used for nunjucks templating is essentially what your provide, I only added a "port" to the options:

```
// Import the library
const server = require('server');
const express = require('express');
const nano = require('nano')('http://localhost:5984');

const settings = require('settings');

const app = express;
const { get, post } = server.router;
const { render, json, redirect, status } = server.reply;

const nunjucks = require('nunjucks');
var env = nunjucks.configure('views'); 

const engine = {
    port: settings.PORT,
  nunjucks: (file, options) => require('nunjucks').render(file, options)
};


server(engine, ctx => render('index.nunjucks', {  }));
```

I hope to eventually contribute documentation as I attempted to before and maybe even code if I can become better at Node :+1: 

### Expected outcome

after running node index.js, I should be able to see the standard HTML template using standard nunjucks templating.

### Actual outcome

```
[Tue Mar 06 2018 17:20:10 GMT-0600 (CST)] ERROR Error: Module "nunjucks" does not provide a view engine.
    at new View (/home/acer/nodespace/node_modules/express/lib/view.js:84:13)
    at Function.render (/home/acer/nodespace/node_modules/express/lib/application.js:570:12)
    at ServerResponse.render (/home/acer/nodespace/node_modules/express/lib/response.js:1008:7)
    at Promise (/home/acer/nodespace/node_modules/server/reply/reply.js:139:13)
    at new Promise (<anonymous>)
    at stack.push.ctx (/home/acer/nodespace/node_modules/server/reply/reply.js:136:26)
    at Reply.exec (/home/acer/nodespace/node_modules/server/reply/reply.js:175:11)
    at processReturn (/home/acer/nodespace/node_modules/server/src/join/index.js:11:22)
    at Object.middle (/home/acer/nodespace/node_modules/server/src/join/index.js:43:17)
    at <anonymous>

```

### Live Demo

No live demo :(

### System Information

Ubuntu 16.04

**Node Version:**  v8.9.1

**Server.js Version:** server@1.1.0-alpha.3

**Comment by dannluciano** [comment]
I think that you should use:
```js
const options = {
    port: settings.PORT,
    engine: {
       'nunjucks': (file, options) => require('nunjucks').render(file, options)
};


server(engine, ctx => render('index.nunjucks', {  }));
```

**Comment by coderam** [comment]
Thanks Dann, but after using the options in server(options, [get( ... ]) the page fails to load at all.  Hoping the documentation improves on this use case (if I can get it working I shall try and volunteer that page in the docs.

```
var options = {
    public: 'static',
    port: settings.PORT,
    session: {
        activated: false,
    }, 

    engine: {
        nunjucks: (file, options) => require('nunjucks').render(file, options)
    }
}; 
```

_**Outcome**_

The page fails to load now.

**Comment by dannluciano** [comment]
What is the error in Console/Terminal?

```settings.PORT``` has a number value?

**Comment by coderam** [comment]
No error in the console, settings.PORT has a value without a question.

Everything was working until upgrading to the alpha3 version used in this post.  I was trying to use the DKIM feature for forms but noticed what you noticed in another issue.  ctx.locals was undefined and so was the dkim value.  I was hoping alpha3 would work, but not yet.

love only,

**Comment by coderam** [comment]
When I say no error, the console just hangs without closing after running node index.js (so there is no error at all).

**Comment by franciscop** [comment]
@dannluciano is right, you need a key `engine` inside options as he explained. His code seems correct, but I am worried about a bit in your code:

```js
public: 'static',
```

Just to make sure, could you share your file structure please? Where are your view files? `public` is for public assets, which `.nunjucks` are not. If your index is under `static` like `static/index.nunjucks`, then you would also have to set the view folder:

```js
var options = {
    public: 'static',
    views: 'static',  // <= added
    port: settings.PORT,
    session: false,   // <= I think you mean this here

    engine: {
        nunjucks: (file, options) => require('nunjucks').render(file, options)
    }
}; 
```

**Comment by coderam** [comment]
Hi @franciscop, index.nunjucks is in the "views" folder as required.  "static" is only for my ".jpg, .css, .js" files.  If you need something to test quickly, feel free to checkout the very simple "mural4peace" app I just invited you to.

**Comment by franciscop** [comment]
Could you share your full entry point please? Should be `index.js` or `server.js`

**Comment by coderam** [comment]
index.js

**Comment by franciscop** [comment]
Could you share your full entry point **code** please? :rofl:

**Comment by coderam** [comment]
just added a package.json file with the dependencies as follows:
"dependencies": {
    "express": "4.16.2",
    "nano": "6.4.3",
    "nunjucks": "3.1.2",
    "server": "1.1.0-alpha.3",
  }

I assume this is what you need to launch the app.  The only 2 non-obvious dependencies are "nano" and "nunjucks" -- once those are installed, simply run "node index.js"

Hope this helps.  Have a good day!!

**Comment by coderam** [comment]
@franciscop not sure what you mean by entry point code??

**Comment by coderam** [comment]
oh you mean the full index.js code :)
```

// Import the library
const server = require('server');
const express = require('express');
const nano = require('nano')('http://localhost:5984');

const settings = require('settings');

const app = express;
const { get, post } = server.router;
const { render, json, redirect, status } = server.reply;

const nunjucks = require('nunjucks');
var env = nunjucks.configure('views'); 

var options = {
    public: 'static',
    port: settings.PORT,
    session: {
        activated: false,
    }, 

    engine: {
        nunjucks: (file, options) => require('nunjucks').render(file, options)
    }
}; 


nano.db.get(settings.COUCHDB_PREFIX+settings.COUCHDB_APP, function(err, hi) {
   if (err) {
       nano.db.create(settings.COUCHDB_PREFIX+settings.COUCHDB_APP, function(err, hi) {
            if (err)
                console.log('db already hi')
            else
                console.log('db hi')
        });
   }
       
});

var treeternities = nano.use(settings.COUCHDB_PREFIX+settings.COUCHDB_APP);

if (settings.LOCAL) {
treeternities.insert({ title: "hi", uplifting: "uplifting", how: "areyouhi" }, function(err, body, header) {
  if (err) {
    console.log('[.insert] ', err.message);
  } else {
      console.log('you have added to the treeternity.', body)
  }
});
}

var treeternities_each = [];

treeternities.list(function(err, body) {
  if (!err) {
    console.log('hi')
    body.rows.forEach(function(doc) {
      //console.log(doc);
        console.log(doc.id);
        treeternities.get(doc.id, function(err,eternity) {
            treeternities_each.push(eternity);
           console.log(eternity); 
        });
    });
  } else {
      
      console.log("error", err);
  }
});

/* 
{% set length = windriders.length if images.length < 13 else 13 %} 
        {% for i in range(0, length) %}
            {{windriders[i] | dump}}
            {{windriders[i]["id"]}} {{windriders[i]._id}}
        {% endfor %}
        */

if (options.session.activated)
    settings.HTML_ONLY = false;

console.log(process.env.REMOTE_ADDR);

server(options,[
  get('/index.html',
        ctx => render('index.nunjucks', 
                                 {  chai: "chai", 
                                    settings: settings,
                                    options: options,
                                    treeternities: treeternities_each
                                 }
                     
        )),
  get('/left-sidebar.html', ctx => nunjucks.render('left-sidebar.hbs', Object.assign({}, ctx.locals, 
                                                                  { chai: "chai", 
                                                                    settings: settings,
                                                                    options: options,
                                                                    treeternities: treeternities_each
                                                                  }))),
  get('/right-sidebar.html', ctx => nunjucks.render('right-sidebar.hbs', Object.assign({}, ctx.locals, 
                                                                  { chai: "chai", 
                                                                    settings: settings,
                                                                    options: options,
                                                                    treeternities: treeternities_each
                                                                  }))),
    
  get('/no-sidebar.html', ctx => nunjucks.render('no-sidebar.hbs', Object.assign({}, ctx.locals, 
                                                                  { chai: "chai", 
                                                                    settings: settings,
                                                                    options: options,
                                                                    treeternities: treeternities_each
                                                                  }))),  
  get('/contact.html', ctx => nunjucks.render('contact.hbs', Object.assign({}, ctx.locals, 
                                                                  { chai: "chai", 
                                                                    settings: settings,
                                                                    options: options,
                                                                    treeternities: treeternities_each
                                                                  }))),
    /* email katherine at 
    walter passmore, get contact info from katherine to walter.  
    lots of organizations in texas and elsewhere 
    alliance for community trees.  arbor day foundation, dana karcher
    putting all orgs on a Map
    california relief maps.
    tree folks
    when we plant where we plant is localized
    who are the partners
    davids birthday 
    small non-profit organizations */
    
  get('/', ctx => {
    console.log(process.env.REMOTE_ADDR);
    return redirect('/index.html');
  }), 
  get('/activated.html', ctx => {
    options.session.activated = true;
    return redirect('/index.html?activated');
  }),
  post('/upload', ctx => json(ctx.data)), 
  get(ctx => status(404))
]);

// Answers to any request
//server(options);

// Answers to any request
//server(options);

```

settings.js

var settings = {};

```
settings.ALLOW_LOGIN = true;
settings.HTML_ONLY = true;
settings.DOMAIN = 'localhost';
settings.PORT = 36367;
settings.COUCHDB_PREFIX = 'peaceparty_';
settings.COUCHDB_APP = 'peaceparty';
settings.LOCAL = true;
settings.EMAIL = 'volunteers@peaceparty.com';
settings.TITLE = "Peace";
module.exports = settings;
```
