### ISSUE TITLE
app.use  |  or express middleware examples

### ISSUE THREAD

**Issue by bradschafer** [franciscop/server#83]
Francisco,

First off.. thanks for the library.. this looks really promising.

I am having a hard time determining how I would go about using the 'use' for Express in 'server'.

I am pretty sure it's simply a syntax thing..

Working Express Example:

```
import express from 'express';
import { graphqlExpress, graphiqlExpress } from 'graphql-server-express';
import bodyParser from 'body-parser';
```

.....

```
export default function(webpackConfig, contentBase) {
  const port = 8080;
  const app = express();

  app.use('/graphql', bodyParser.json(), graphqlExpress({ 
    schema,
    printErrors: true
  }));

  app.use('/graphiql', graphiqlExpress({ endpointURL: '/graphql' }));
  app.use(express.static(contentBase));

  if (process.env.NODE_ENV !== 'production') {
      const webpackMiddleware = require("webpack-dev-middleware");
      app.use(webpackMiddleware(webpack(webpackConfig)));
  }

  app.listen(port, () => console.log(
    `GraphiQL is now running on http://localhost:${port}/graphiql`
  ));
}
```

... attempted with Serverjs

```

 import server from 'server';
 import { get, put, del, post, error } from  'server/router';
```

```
export default function(webpackConfig, contentBase) {
  
  const options = {
        //favicon: 'public/favicon.png',
        port: process.env.PORT || 8080,
        public: contentBase,
        parser: {
            body: { limit: '1mb' },
            json: { limit: '10mb' }
        }
      
      };
  
  const routes = [
        //graphql engine
        get('/graphql', ctx => server.utils.modern( graphqlExpress({ 
            schema,
            printErrors: true
          }))
        ),

        //visualiztion
        get('/graphiql', ctx => server.utils.modern( graphiqlExpress({ endpointURL: '/graphql' })) )   
        
  ]    

  server(options, routes , error(ctx => status(500).send(ctx.error.message)));

}


```
I am assuming the option **public:contentBase** works similar to the  express static content base.

I am not sure why there isn't a  'use' as I want all the verbs to be handled..

The error is below..

But my main question what syntax should I be using for the express middleware to pump it back into server? 

How would I implement something like this?
`  app.use(express.static(contentBase));`

- 
- How would I go about the 'conditional' middleware in the working example?
- Would I pass an empty array or null?
- or can I call server again after it's been called already to add them?

error:

 ```
{ Error: 

Your middleware did not return anything to the user. This normally happens when no route was matched or if the router did not reply with anything.



This won't return anything:



~~~

// BAD

server(ctx => {

  console.log('Hello world');

});

~~~



Make sure that something is returned from your middlware so a reply is sent to the user:



~~~

// GOOD:

// Return with an arrow function

server(ctx => 'Hello world');



// Return with a explicit return

server(ctx => {

  // ...

  return 'Hello world';

});



// Return a simple status code:

server(ctx => 200);

~~~



Read the full documentation for reply here:

https://serverjs.io/documentation/reply/



    at buildError (/Volumes/Data/GitHub/bradschafer/manifold/packages/manifold-server/node_modules/server/error/index.js:2:17)

    at new ErrorInstance (/Volumes/Data/GitHub/bradschafer/manifold/packages/manifold-server/node_modules/server/error/index.js:19:12)

    at handler (/Volumes/Data/GitHub/bradschafer/manifold/packages/manifold-server/node_modules/server/plugins/final/index.js:15:21)

    at Object.middle (/Volumes/Data/GitHub/bradschafer/manifold/packages/manifold-server/node_modules/server/src/join/index.js:42:27)

    at <anonymous>

  status: 500,

  namespace: '/plugin/final/',

  code: '/plugin/final/noreturn',

  id: 'plugin-final-noreturn' }




```

Thanks,

Brad

PS: Is there a slack channel or something for this project?

**Comment by franciscop** [comment]
Hi Brad, thanks for the issue! First some tips:

## `public` [Documentation](https://serverjs.io/documentation/options/#public)

The static middleware is included by default, you just need to add the `public` option:

```js
const options = { public: contentBase };
```

## `modern()` [Documentation](https://serverjs.io/documentation/#express-middleware)

Modern will apply it plainly, so no need for `ctx => modern()` (actually I think that might not work):

```js
// This bit:
get('/graphql', ctx => server.utils.modern(graphqlExpress(...)))

// Should be:
get('/graphql', server.utils.modern(graphqlExpress(...)))

// Also this bit
get('/graphiql', ctx => server.utils.modern(...))

// Should be this:
get('/graphiql', server.utils.modern(...))
```


With these two recommendations, I'd refactor the code like this:

```js
export default function(webpackConfig, public) {
  
  const options = {
        public,  // renamed on the argument so 
        port: 8080,  // Will already use the env if provided
        parser: {
            body: { limit: '1mb' },
            json: { limit: '10mb' }
        }
      };

  const routes = [
        get('/graphql', server.utils.modern( graphqlExpress({ schema, printErrors: true }))),
        get('/graphiql', ctx => server.utils.modern( graphiqlExpress({ endpointURL: '/graphql' })))
  ];

  server(options, routes , error(ctx => status(500).send(ctx.error.message)));
};
```

### `use()`

`.use()` in server.js would be similar to just another argument since that just adds a middleware. If you want any generic router, right now you can either add a plain middleware:

```js
server(options, routes, ctx => {
  // All of the routes, *including* the ones already matched like `/graphql`
}, error(...));
```

But this will not care about others. You can also do this:

```js
const any = ctx => {
  return 'Any method for /';
};

const home = [get('/', any), post('/', any), put('/', any), del('/', any)];

server(options, home, routes, error(...)).then(...);
```

I am considering adding an `all()` route that does this behaviour similar to express, but so far you'll have to repeat those. If you find yourself really needing it now, you could just implement it yourself exactly like this:

```js
const all = (path, ...middle) => [
  get(path, ...middle),
  post(path, ...middle),
  put(path, ...middle),
  del(path, ...middle),
];

const home = all('/', ctx => 'Any method from homepage :)');

server(options, home, routes, error(...)).then(...);
```

**Comment by franciscop** [comment]
About the optional middleware, you cannot call server again by itself, but this issue might be useful: https://github.com/franciscop/server/issues/61

To do it with server, you can pass both null or an empty array:

```js
const a = true;

server(a ? modern(myLib) : null);
```
