### ISSUE TITLE
Server Crashes in docker

### ISSUE THREAD

**Issue by vorticalbox** [franciscop/server#90]
### Description

Server fails to start when run in a  docker image

### Expected outcome

Server does crash

### Actual outcome

Crashes with 
```
roduction-general_1  | 09:22:10 - error:  json: 
production-general_1  |   The option 'json' should be a '[object]' but you passed a 'undefined':
production-general_1  |   "timeline-worker.json"
production-general_1  |     at buildError (/usr/src/app/node_modules/server/error/index.js:2:17)
production-general_1  |     at new ErrorInstance (/usr/src/app/node_modules/server/error/index.js:19:12)
production-general_1  |     at module.exports (/usr/src/app/node_modules/server/src/config/parse.js:139:15)
production-general_1  |     at Promise.all.plugins.map (/usr/src/app/node_modules/server/src/config/index.js:14:27)
production-general_1  |     at Array.map (<anonymous>)
production-general_1  |     at module.exports (/usr/src/app/node_modules/server/src/config/index.js:13:29)
production-general_1  |     at <anonymous>
production-general_1  |     at process._tickDomainCallback (internal/process/next_tick.js:228:7)
production-general_1  |     at Function.Module.runMain (module.js:695:11)
production-general_1  |     at startup (bootstrap_node.js:188:16)
production-general_1  |     at bootstrap_node.js:609:3

```

### System Information

docker 1.13.1

**Node Version:** v8.10.0

**Server.js Version:** 1.0.14

**Comment by vorticalbox** [comment]
turns out not a problem with ServerJs as the copying directly into a docker image works fine

**Comment by franciscop** [comment]
Glad to hear. Would recommend setting `server({ parser: { json: {} } });` manually otherwise. It seems you fixed it and now I'm on holiday, if you give some more info I'll try to debug it better when I'm back.
