### ISSUE TITLE
ERROR { TypeError: Cannot read property 'headersSent' of undefined

### ISSUE THREAD

**Issue by karneaud** [franciscop/server#98]
**What are you trying to do?**
Trying to test the following controller with socket method callbacks

controller socket methods

```
// routes
module.exports = [
  get('/', ctx => render('index')),
  get('/console', ctx => render('console')),
  get('/player', ctx => render('player')),
  socket('console', ctrl.console),
  socket('player', ctrl.player)
];
// ctrl 
  console (r) {
    let { socket, data, path, io } = r, g
    if(!(socket.id in games))  {
      g = games[socket.id] = new Game( socket.id )
      socket.on('disconnect',  () => ctlr.leave(socket.id) )
    }

    socket.emit('message', { state : Game.READY, id: socket.id })
  },
  player (r) {
    let { socket, data, path, io } = r, p
    console.re.log(data.id, 'id');
    if(!(socket.id in players) && (data.id in games)) {
      p = players[socket.id] = new Player(id, data.id )
      // socket.join(data.id)
      // console.re.log('player connecting to game ID ', data.id, Player.READY );
      // socket.to(data.id).emit('message', { state: Player.CONNECTED })
      socket.on('disconnect',  () => ctlr.leave(socket.id) )
    }

    socket.emit("message", { state: Player.READY  })
  },
```

**Have you tried this first?**

- [x] Try to find an answer by reading [the documentation](https://serverjs.io/documentation/) and [tutorials](https://serverjs.io/tutorials/).
- [x] Try to find an answer by searching [previous Github issues](https://github.com/franciscop/server/issues/).
- [x] Try to find an answer by searching the Web.
- [ ] Try to find an answer by inspection or experimentation.
- [ ] Try to find an answer by asking a skilled friend.
- [ ] Try to find an answer by reading the source code.

**Ask your question**
I'm trying to run the following test case to test the above controller socket methods where game connects to "console" and player  connects to 'player' 

```

.....
routes.push(socket('console', ctlr.console ))
          routes.push(socket('player', ctlr.player ))
          await test( routes ).run(async api => {
            port = api.ctx.options.port
            game = io(`http://localhost:${port}`)
            game.on('connect', async () => {
              game.on('message', (s) => {
                gameResp = s.state
                gameID = s.id

                player = io(`http://localhost:${port}`)
                player.on('connect', async () => {
                  // player.on('message', (s) => {
                  //   playerResp = s.state
                  //   console.re.log('playerResp', playerResp );
                  //   //player.disconnect()
                  // })
                  
                  player.emit('player', { id: gameID  })
                })

              })

....
```

But get the following error

> ERROR { TypeError: Cannot read property 'headersSent' of undefined
    at Array.module.exports.server.router.error.ctx (/usr/src/app/node_modules/server/test/handler.js:4:15)
    at Function.generic.error (/usr/src/app/node_modules/server/router/error.js:19:32)
    at Object.middle (/usr/src/app/node_modules/server/utils/join/index.js:47:33)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7) code: '', params: {} }

**Environment (optional):**
 - OS: Docker 
 - Node.js: 8
 - Server.js: server@1.1.0-alpha.9

**Additional context (optional)**

I'm running the code using mochajs with --delay for async cases.

**Comment by karneaud** [comment]
figured it out! please delete this issue
